[[CURRENCIES]]
code = "JPT"
issuer = "GACLIJDIBJQQZHDVLHH6GMEAAOR7MHFX4XICVCVEWTCYIOCSBLI72BK3"
name = "jengapay"
desc = "token maalum kwa malipo ya ujenzi"
image = "https://i.postimg.cc/26dv0hvK/file-000000002d9071f48e01dcae77e2cbf8.png"
